#version: '3.8'
name: expense
networks:
  default:
    name: expense
services:
  mysql:
    image: mysql:v1
    container_name: mysql
  backend:
    image: backend:v1
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on: 
    - mysql
  frontend:
    image: frontend:v1
    container_name: frontend
    depends_on:
    - backend 
    ports:
    - "80:80" 
